DROP TABLE IF EXISTS `INTERNAL_USER`;
CREATE TABLE `INTERNAL_USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `USER_CREDENTIAL`;
CREATE TABLE `USER_CREDENTIAL` (
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`USERNAME`),
  KEY `FK_USER_ID_idx` (`USER_ID`),
  CONSTRAINT `FK_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `INTERNAL_USER` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `USER_ROLES`;
CREATE TABLE `USER_ROLES` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `ROLE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `UNIQUE_KEY` (`USERNAME`,`ROLE`),
  KEY `FK_USERNAME_idx` (`USERNAME`),
  CONSTRAINT `FK_USERNAME` FOREIGN KEY (`USERNAME`) REFERENCES `USER_CREDENTIAL` (`USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;